version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - gu install native-image
    on-failure: ABORT
  build:
    commands:
      - echo Build started on `date`
      - java -jar /leiningen-2.9.3-standalone.jar -m leiningen.core.main install
      - cd lambda
      - cp bootstrap /
      - cp template-native.yml /
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /bootstrap
    - /output
    - /template-native.yml
