AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Menard lambda functions using using the `holy-lambda` micro library"
Parameters:
  Runtime:
    Type: String
    Default: provided
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  BucketName:
    Type: String
  ObjectKey:
    Type: String
Globals:
  Function:
    Runtime: !Ref 'Runtime'
    Timeout: !Ref 'Timeout'
    MemorySize: !Ref 'MemorySize'
Resources:
  GenerateNL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: menard.lambda.core.GenerateNL
      CodeUri:
        Key: !Ref 'ObjectKey'
        Bucket: !Ref 'BucketName'
      FunctionName: MenardGenerateNL
      Events:
        Event:
          Type: Api
          Properties:
            Path: /generate
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
          Type: AllAtOnce
  ParseNL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: menard.lambda.core.ParseNL
      CodeUri:
        Key: !Ref 'ObjectKey'
        Bucket: !Ref 'BucketName'
      FunctionName: MenardParseNL
      Events:
       Event:
          Type: Api
          Properties:
            Path: /parse
            Method: get
      AutoPublishAlias: live
      DeploymentPreference:
          Type: AllAtOnce
